# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac2de644dfc0bdfafe33b9b1ee851a28151497e553b0b2da443114e8eb1c75270bc4225353332cbaf7aa609a1387780edfcf0779cce11454a3b533b7458edd57

test:
  secret_key_base: d9a1ce028836f1f977bacdc4c1b3b5bc24271f9ceab2fb3697b8117732d828b4a556c8131e5d2c16c8b74ae2538d7522026b4e4c4ad2379335770efa35719dae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
